version: "3.7"

services:
  caddy:
    build: caddy
    command: caddy run --config /etc/caddy/Caddyfile
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/cert:/data/caddy/certificates/local/localhost
  
  webhook:
    build: .
    restart: unless-stopped
    volumes:
      - ${PWD}/webhook.yaml:/webhook.yaml
      - ${PWD}/bmc.py:/bmc.py
      - caddy_data:/data

  # This allows access to the certificate file on the host machine for non root users.
  cert-permission:
    image: bash:4.4
    command: -c "
      cp -a /data/caddy/certificates/local/localhost/localhost.crt /data/caddy/certificates/local/localhost/localhost-copy.crt;
      chmod 777 /data/caddy/certificates/local/localhost/localhost-copy.crt;"
    restart: on-failure
    volumes:
      - caddy_data:/data
      - ${PWD}/cert:/data/caddy/certificates/local/localhost
    depends_on:
      caddy:
        condition: service_started

volumes:
  caddy_data:
  caddy_config:
