name: For each commit and PR
on:
  push:
    branches:
      - "**"
    tags:
      - "v**"
  pull_request:

env:
  KERNEL_MODE: docker
  MKOSI_MODE: native

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup-mkosi
        uses: systemd/mkosi@v26
    
      - name: build
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap
          ./build.py build